<?php

/**
 * @file
 * Contains soapbox_related_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function soapbox_related_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the soapbox_related_content module.
    case 'help.page.soapbox_related_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper services for related contents.') . '</p>';
      return $output;

    default:
  }
}
